data:
  # src_pc1: D:\GitHubProjects\Terranum_repo\pc_movement_tracking\data\test_20_nb_iterations\swisssurface3d_2018_2589-1169_2056_5728.ply
  # src_pc2: D:\GitHubProjects\Terranum_repo\pc_movement_tracking\data\test_20_nb_iterations\swisssurface3d_2024_2589-1169_2056_5728.ply
  # src_res: D:\GitHubProjects\Terranum_repo\pc_movement_tracking\data\test_24_point_to_plane\test
  # src_pc1: D:\GitHubProjects\Terranum_repo\pc_movement_tracking\data\test_21_directly_from_las\swisssurface3d_2018_2588-1169_2056_5728.las
  # src_pc2: D:\GitHubProjects\Terranum_repo\pc_movement_tracking\data\test_21_directly_from_las\swisssurface3d_2024_2588-1169_2056_5728.copc.laz
  # src_res: D:\GitHubProjects\Terranum_repo\pc_movement_tracking\data\test_21_directly_from_las\results_clipping_centering
  src_pc1: data/test_one_tile/swisssurface3d_2018_2563_1145_2056_5728.las
  src_pc2: data/test_one_tile/swisssurface3d_2024_2563_1145_2056_5728.copc.laz
  src_res: default
  res_suffixe: test
args:
  method: pointtopoint  # choose between pointtopoint and pointtoplane
  pointtoplane_radius: 2.0
  pointtoplane_max_nn: 50
  pointtoplane_min_nn: 10
  max_iteration: 100
  threshold: 1e-4
  min_tile_size: 128
  min_points: 2000
  min_tile_size_ground: 128
  min_tile_size_anthropic: 128
  min_points_ground: 2000
  min_points_anthropic: 50
  huge_translation: [2589500, 1169500, 0]
  category: all
  do_output_transformed: True
  output_level: -1 # -1 to output at each level
  do_preprocessing: False
  do_postprocessing: True
  verbose: True
to_keep:
  full_tree: True
  layers: True
  initial_alignment: both # choose between {'with', 'without', 'both'}
preprocessing:
  list_cat_to_remove: [1, 3, 9, 14, 15]
  cat_ground: 2
  do_keep_sf: False
postprocessing:
  src_transforms: default
  absurd_dist: 5
  verbose: False